# Generated by Django 6.1 on 2026-08-08 20:34

import communications.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0007_employeemodulepermission'),
        ('shops', '0025_company_communications_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppBridgeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('disconnected', 'Disconnected'), ('qr_pending', 'QR pending'), ('connected', 'Connected')], db_index=True, default='disconnected', max_length=20)),
                ('qr_data_url', models.TextField(blank=True, default='')),
                ('wa_phone', models.CharField(blank=True, default='', max_length=40)),
                ('last_error', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp bridge state',
                'verbose_name_plural': 'WhatsApp bridge state',
            },
        ),
        migrations.CreateModel(
            name='BroadcastCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_template', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=communications.models.campaign_image_path)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('sending', 'Sending'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_campaigns', to='employees.employeeprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(db_index=True, max_length=40)),
                ('body', models.TextField()),
                ('image_path', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('manual_review', 'Manual review')], db_index=True, default='pending', max_length=20)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.broadcastcampaign')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_messages', to='shops.client')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['campaign', 'status'], name='communicati_campaig_d4e6d0_idx')],
            },
        ),
    ]
