# Generated by Django 5.0.14 on 2026-08-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('super_admin', 'Super Admin'), ('company_manager', 'Company Manager'), ('shop_manager', 'Shop Manager'), ('shop_cashier', 'Shop Cashier'), ('it_support', 'IT Support')], db_index=True, default='employee', max_length=32),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended')], db_index=True, default='pending_approval', max_length=32),
        ),
    ]
