# Generated by Django 6.1 on 2026-08-06 09:02

import employees.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_role_status_mysql_enum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='role',
            field=employees.fields.MysqlEnumField(choices=[('employee', 'Employee'), ('super_admin', 'Super Admin'), ('company_manager', 'Company Manager'), ('shop_manager', 'Shop Manager'), ('shop_cashier', 'Shop Cashier'), ('it_support', 'IT Support')], db_index=True, default='employee', enum_values=['employee', 'super_admin', 'company_manager', 'shop_manager', 'shop_cashier', 'it_support'], max_length=15),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='status',
            field=employees.fields.MysqlEnumField(choices=[('pending_approval', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended')], db_index=True, default='pending_approval', enum_values=['pending_approval', 'active', 'suspended'], max_length=16),
        ),
    ]
