# Generated by Django 6.1

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_alter_employeeprofile_role_and_more"),
        ("shops", "0002_shop_password_and_login_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="assigned_shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_employees",
                to="shops.shop",
            ),
        ),
    ]
