# Generated by Django 6.1

from django.db import migrations, models


def copy_assigned_shop_to_m2m(apps, schema_editor):
    EmployeeProfile = apps.get_model("employees", "EmployeeProfile")
    Through = EmployeeProfile.assigned_shops.through
    rows = []
    for profile in EmployeeProfile.objects.exclude(assigned_shop_id=None).iterator():
        rows.append(
            Through(
                employeeprofile_id=profile.pk,
                shop_id=profile.assigned_shop_id,
            )
        )
    if rows:
        Through.objects.bulk_create(rows, ignore_conflicts=True)


def copy_m2m_back_to_assigned_shop(apps, schema_editor):
    EmployeeProfile = apps.get_model("employees", "EmployeeProfile")
    Through = EmployeeProfile.assigned_shops.through
    first_shop_by_profile = {}
    for row in Through.objects.order_by("id").iterator():
        first_shop_by_profile.setdefault(row.employeeprofile_id, row.shop_id)

    for profile in EmployeeProfile.objects.iterator():
        profile.assigned_shop_id = first_shop_by_profile.get(profile.pk)
        profile.save(update_fields=["assigned_shop_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_employeeprofile_assigned_shop"),
        ("shops", "0002_shop_password_and_login_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="assigned_shops",
            field=models.ManyToManyField(blank=True, to="shops.shop"),
        ),
        migrations.RunPython(copy_assigned_shop_to_m2m, copy_m2m_back_to_assigned_shop),
        migrations.RemoveField(
            model_name="employeeprofile",
            name="assigned_shop",
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="assigned_shops",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_employees",
                to="shops.shop",
            ),
        ),
    ]
