# Generated by Django 6.1 on 2026-08-06 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employeeprofile_assigned_shops'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_slug', models.CharField(db_index=True, max_length=64)),
                ('submodule_slug', models.CharField(db_index=True, max_length=64)),
                ('allowed', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='employees.employeeprofile')),
            ],
            options={
                'ordering': ['module_slug', 'submodule_slug', 'employee_id'],
                'indexes': [models.Index(fields=['module_slug', 'submodule_slug'], name='emp_mod_submod_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'module_slug', 'submodule_slug'), name='uniq_employee_module_submodule_perm')],
            },
        ),
    ]
