# Generated by Django 6.1 on 2026-08-06 09:38

import django.db.models.deletion
import items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_alter_employeeprofile_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=120)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('minimum_selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('maximum_selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('shop_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to=items.models.item_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_created', to='employees.employeeprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
