# Generated by Django 6.1 on 2026-08-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_suspended',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
