# Generated by Django 6.1 on 2026-08-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_stock_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('partial', 'Partial')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='stockmovementline',
            name='buying_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockmovementline',
            name='reason',
            field=models.CharField(blank=True, choices=[('waste', 'Waste'), ('transfer', 'Transfer'), ('display', 'Display'), ('return', 'Return')], default='', max_length=16),
        ),
    ]
