# Generated by Django 6.1 on 2026-08-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_stock_movement_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovementline',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stockmovementline',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('partial', 'Partial')], default='', max_length=16),
        ),
    ]
