# Generated by Django 6.1 on 2026-08-06 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_stock_line_per_item_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovementline',
            name='serial_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ItemSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=120)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serials', to='items.item')),
            ],
            options={
                'ordering': ['serial_number'],
                'constraints': [models.UniqueConstraint(fields=('item', 'serial_number'), name='uniq_item_serial_number')],
            },
        ),
    ]
