# Generated by Django 6.1 on 2026-08-06 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_item_serial_tracking'),
        ('shops', '0002_shop_password_and_login_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemserial',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_serials', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='shops.shop'),
        ),
        migrations.CreateModel(
            name='ShopStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_stocks', to='items.item')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_stocks', to='shops.shop')),
            ],
            options={
                'ordering': ['shop__name', 'item__name'],
                'constraints': [models.UniqueConstraint(fields=('shop', 'item'), name='uniq_shop_item_stock')],
            },
        ),
    ]
