# Generated by Django 6.1 on 2026-08-06 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_shop_stock_matrix'),
        ('shops', '0002_shop_password_and_login_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='requested_from_shop',
            field=models.ForeignKey(blank=True, help_text='For requests: the shop being asked to supply stock.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_requests_received', to='shops.shop'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='Shop performing stock in/out, or the shop requesting stock.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='shops.shop'),
        ),
    ]
