# Generated by Django 6.1 on 2026-08-06 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_stock_movement_requested_from_shop'),
        ('shops', '0002_shop_password_and_login_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='use_individual_shop_prices',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='ShopItemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_prices', to='items.item')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_prices', to='shops.shop')),
            ],
            options={
                'ordering': ['shop__name', 'item__name'],
                'constraints': [models.UniqueConstraint(fields=('shop', 'item'), name='uniq_shop_item_price')],
            },
        ),
    ]
