# Generated by Django 6.1 on 2026-08-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_stock_request_response_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='request_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('declined', 'Declined')], db_index=True, default='', help_text='Used for stock requests only.', max_length=16),
        ),
    ]
