# Generated by Django 6.1 on 2026-08-07 19:46

from decimal import Decimal

from django.db import migrations, models


def backfill_stock_amount_paid(apps, schema_editor):
    StockMovement = apps.get_model("items", "StockMovement")
    StockMovementLine = apps.get_model("items", "StockMovementLine")
    zero = Decimal("0.00")
    for movement in StockMovement.objects.filter(movement_type="in").iterator():
        lines = list(
            StockMovementLine.objects.filter(movement_id=movement.pk).only(
                "quantity", "buying_price", "payment_status"
            )
        )
        if not lines:
            continue
        paid_total = zero
        all_paid = True
        any_paid = False
        for line in lines:
            qty = int(line.quantity or 0)
            unit = Decimal(line.buying_price or 0)
            line_total = (unit * qty).quantize(Decimal("0.01"))
            status = (line.payment_status or "").strip()
            if status == "paid":
                paid_total += line_total
                any_paid = True
            else:
                all_paid = False
                if status == "partial":
                    any_paid = True
        if all_paid:
            status = "paid"
            paid_total = sum(
                (
                    (Decimal(line.buying_price or 0) * int(line.quantity or 0)).quantize(
                        Decimal("0.01")
                    )
                    for line in lines
                ),
                zero,
            )
        elif any_paid:
            status = "partial"
        else:
            status = (
                "unpaid"
                if any((line.payment_status or "").strip() for line in lines)
                else ""
            )
            paid_total = zero
        StockMovement.objects.filter(pk=movement.pk).update(
            amount_paid=paid_total,
            payment_status=status or movement.payment_status,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0018_stock_movement_load_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RunPython(backfill_stock_amount_paid, migrations.RunPython.noop),
    ]
