# Generated by Django 6.1 on 2026-08-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_stockmovementline_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='low_stock_notify',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=0, help_text='Alert when total stock across shops is at or below this quantity.'),
        ),
    ]
