# Generated by Django 6.1 on 2026-08-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0028_remove_item_maximum_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='entry_source',
            field=models.CharField(blank=True, choices=[('buy_items', 'Buy items'), ('stock_management', 'Stock management')], db_index=True, default='', help_text='UI entry point that created this movement. Blank for legacy rows created before this field existed.', max_length=32),
        ),
    ]
