# Generated by Django 6.1 on 2026-08-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0031_shopstock_low_stock_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='avg_buy_qty',
            field=models.PositiveIntegerField(default=1, help_text='Typical quantity a customer buys of this item.'),
        ),
        migrations.AddField(
            model_name='item',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='KSh off the list price per unit when the volume quantity is met.', max_digits=12),
        ),
        migrations.AddField(
            model_name='item',
            name='discount_min_qty',
            field=models.PositiveIntegerField(default=0, help_text='Buy this many or more to unlock the volume discount. 0 disables it.'),
        ),
    ]
