# Generated by Django 5.0.14 on 2026-09-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0034_materialize_shop_item_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='entry_source',
            field=models.CharField(blank=True, choices=[('buy_items', 'Buy items'), ('stock_management', 'Stock management'), ('customer_return', 'Customer return'), ('trade_out', 'Trade out'), ('trade_exchange', 'Trade exchange')], db_index=True, default='', help_text='UI entry point that created this movement. Blank for legacy rows created before this field existed.', max_length=32),
        ),
        migrations.AlterField(
            model_name='stockmovementline',
            name='reason',
            field=models.CharField(blank=True, choices=[('waste', 'Waste'), ('transfer', 'Transfer'), ('display', 'Display'), ('return', 'Supplier return'), ('trade_out', 'Trade out')], default='', max_length=16),
        ),
    ]
