# Generated by Django 5.0.14 on 2026-09-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0035_trade_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovementline',
            name='reason',
            field=models.CharField(blank=True, choices=[('waste', 'Waste'), ('transfer', 'Transfer'), ('display', 'Display'), ('return', 'Supplier return'), ('trade_out', 'Trade out'), ('custom', 'Custom')], default='', max_length=16),
        ),
    ]
