# Generated by Django 5.0.14 on 2026-10-05 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_fix_assigned_shops_id_autoincrement'),
        ('items', '0037_decimal_stock_quantity'),
        ('shops', '0069_shopreceiptline_return_batches_reason_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, default='', max_length=200)),
                ('item_category', models.CharField(blank=True, default='', max_length=120)),
                ('kind', models.CharField(choices=[('registered', 'Registered'), ('edited', 'Edited'), ('discount_updated', 'Discount updated'), ('suspended', 'Suspended'), ('unsuspended', 'Unsuspended'), ('deleted', 'Deleted')], db_index=True, max_length=32)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_activity_events', to='employees.employeeprofile')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to='items.item')),
                ('shops', models.ManyToManyField(blank=True, related_name='item_activity_events', to='shops.shop')),
            ],
            options={
                'ordering': ['-occurred_at', '-pk'],
                'indexes': [models.Index(fields=['kind', '-occurred_at'], name='items_itema_kind_occurred_idx'), models.Index(fields=['actor', '-occurred_at'], name='items_itema_actor_occurred_idx')],
            },
        ),
    ]
