# Generated by Django 5.0.14 on 2026-10-07 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0039_stockmovement_rider_name'),
        ('shops', '0069_shopreceiptline_return_batches_reason_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('request', 'Transfer Stock')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='request_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('declined', 'Declined')], db_index=True, default='', help_text='Used for inter-shop transfers only.', max_length=16),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='requested_from_shop',
            field=models.ForeignKey(blank=True, help_text='For transfers: the shop receiving the stock (notified to confirm).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_requests_received', to='shops.shop'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='requester_notified',
            field=models.BooleanField(default=True, help_text='False after a decision until the sending shop acknowledges it.'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='Shop performing stock in/out, or the shop sending a transfer.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='shops.shop'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='supplier_notified',
            field=models.BooleanField(default=True, help_text='False after a new transfer until the receiving shop acknowledges it.'),
        ),
    ]
