# Generated by Django 6.1 on 2026-08-07 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_companypossettings_printing'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shopdaysession',
            name='uniq_open_shop_day_session',
        ),
    ]
