# Generated by Django 6.1 on 2026-08-07 19:46

from decimal import Decimal

from django.db import migrations, models


def backfill_amount_paid(apps, schema_editor):
    Expense = apps.get_model("shops", "Expense")
    for expense in Expense.objects.all().only("id", "amount", "payment_status"):
        if expense.payment_status == "paid":
            Expense.objects.filter(pk=expense.pk).update(
                amount_paid=expense.amount or Decimal("0")
            )
        else:
            Expense.objects.filter(pk=expense.pk).update(amount_paid=Decimal("0"))


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0019_shop_receipt_returns"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="shopreceipt",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RunPython(backfill_amount_paid, migrations.RunPython.noop),
    ]
