# Generated by Django 6.1 on 2026-08-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0020_amount_paid_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDarajaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_stk_push', models.BooleanField(default=False)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=16)),
                ('consumer_key', models.CharField(blank=True, default='', max_length=255)),
                ('consumer_secret', models.CharField(blank=True, default='', max_length=255)),
                ('passkey', models.CharField(blank=True, default='', max_length=255)),
                ('shortcode', models.CharField(blank=True, default='', max_length=20)),
                ('credentials_valid', models.BooleanField(default=False)),
                ('credentials_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Daraja settings',
                'verbose_name_plural': 'Company Daraja settings',
            },
        ),
    ]
