# Generated by Django 6.1 on 2026-08-07 20:14

import django.db.models.deletion
import shops.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0007_employeemodulepermission"),
        ("shops", "0021_company_daraja_settings"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="shopreceipt",
                    name="mpesa_receipt_number",
                    field=models.CharField(blank=True, default="", max_length=40),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MpesaStkPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        db_index=True,
                        default=shops.models._new_stk_public_id,
                        editable=False,
                        max_length=36,
                        unique=True,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("sale", "Sale checkout"),
                            ("credit", "Credit account pay"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("phone", models.CharField(db_index=True, max_length=20)),
                (
                    "account_reference",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "merchant_request_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "checkout_request_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "mpesa_receipt_number",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=40
                    ),
                ),
                ("result_code", models.CharField(blank=True, default="", max_length=16)),
                (
                    "result_desc",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "account_kind",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("account_id", models.PositiveIntegerField(blank=True, null=True)),
                ("applied", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mpesa_stk_payments",
                        to="employees.employeeprofile",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stk_payments",
                        to="shops.shopreceipt",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mpesa_stk_payments",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
