# Generated by Django 6.1 on 2026-08-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0022_mpesa_stk_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydarajasettings',
            name='callback_base_url',
            field=models.CharField(blank=True, default='', help_text='Public HTTPS base URL for STK callbacks (e.g. https://xxxx.ngrok-free.app).', max_length=255),
        ),
    ]
