# Generated by Django 6.1 on 2026-08-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0025_company_communications_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companycommunicationssettings',
            options={'verbose_name': 'Company WhatsApp settings', 'verbose_name_plural': 'Company WhatsApp settings'},
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('utilities', 'Utilities'), ('transport', 'Transport'), ('salaries', 'Salaries'), ('packaging', 'Packaging'), ('maintenance', 'Maintenance'), ('marketing', 'Marketing'), ('office', 'Office supplies'), ('security', 'Security'), ('food', 'Food & refreshments'), ('owner_drawings', 'Owner drawings'), ('misc', 'Miscellaneous')], db_index=True, max_length=32),
        ),
    ]
