# Generated by Django 6.1 on 2026-08-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0030_shopreceipt_mpesa_receipt_number_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companystocksettings',
            name='enable_supplier_last4_search',
            field=models.BooleanField(default=False),
        ),
    ]
