# Generated by Django 6.1 on 2026-08-18 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0044_whatsapp_item_catalogue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companycommunicationssettings',
            options={'verbose_name': 'Company Twilio settings', 'verbose_name_plural': 'Company Twilio settings'},
        ),
    ]
