# Generated by Django 6.1 on 2026-08-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0047_shopreceipt_shop_created_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDeveloperPaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompts_enabled', models.BooleanField(default=False)),
                ('system_subscription_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('whatsapp_subscription_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hosting_subscription_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prompt_cadence', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annually', 'Semi-annually'), ('annually', 'Annually')], default='monthly', max_length=20)),
                ('popup_location', models.CharField(choices=[('shop', 'Shop page'), ('employee', 'Employee page'), ('both', 'Both')], default='both', max_length=16)),
                ('allow_dismiss', models.BooleanField(default=True, help_text='When off, the dismiss control is hidden and payment is compulsory.')),
                ('last_paid_at', models.DateTimeField(blank=True, null=True)),
                ('last_mpesa_receipt', models.CharField(blank=True, default='', max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company developer payment settings',
                'verbose_name_plural': 'Company developer payment settings',
            },
        ),
        migrations.AlterField(
            model_name='mpesastkpayment',
            name='purpose',
            field=models.CharField(choices=[('sale', 'Sale checkout'), ('credit', 'Credit account pay'), ('developer', 'Developer subscription')], db_index=True, max_length=16),
        ),
    ]
