# Generated by Django 5.0.14 on 2026-09-04 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0052_daraja_stk_hardening'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopPosSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_pos', models.BooleanField(default=False, help_text='When on, shop POS values replace company POS defaults.')),
                ('override_receipt', models.BooleanField(default=False, help_text='When on, shop receipt values replace company receipt defaults.')),
                ('enable_sale', models.BooleanField(default=True)),
                ('enable_credit', models.BooleanField(default=True)),
                ('enable_quotation', models.BooleanField(default=True)),
                ('enable_cash_sale_checkout', models.BooleanField(default=True)),
                ('enable_cash', models.BooleanField(default=True)),
                ('enable_mpesa', models.BooleanField(default=True)),
                ('enable_cash_mpesa', models.BooleanField(default=True)),
                ('enable_discount', models.BooleanField(default=True)),
                ('enable_tax', models.BooleanField(default=False)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('compulsory_print_on_sale', models.BooleanField(default=False)),
                ('enable_print_bluetooth', models.BooleanField(default=True)),
                ('enable_print_usb', models.BooleanField(default=True)),
                ('enable_print_wifi', models.BooleanField(default=True)),
                ('receipt_paper_width', models.CharField(choices=[('80', '80 mm'), ('58', '58 mm')], default='80', max_length=8)),
                ('receipt_format_sale', models.CharField(default='S', max_length=8)),
                ('receipt_format_credit', models.CharField(default='C', max_length=8)),
                ('receipt_format_quotation', models.CharField(default='Q', max_length=8)),
                ('mpesa_collection_type', models.CharField(blank=True, choices=[('paybill', 'Paybill'), ('buy_goods', 'Buy Goods')], default='', max_length=16)),
                ('mpesa_business_number', models.CharField(blank=True, default='', max_length=20)),
                ('mpesa_account_number', models.CharField(blank=True, default='', max_length=40)),
                ('mpesa_till_number', models.CharField(blank=True, default='', max_length=20)),
                ('receipt_font_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'Extra large')], default='medium', max_length=16)),
                ('receipt_font_weight', models.CharField(choices=[('regular', 'Regular'), ('medium', 'Medium'), ('bold', 'Bold'), ('extrabold', 'Extra bold')], default='regular', max_length=16)),
                ('enable_receipt_qr', models.BooleanField(default=False)),
                ('receipt_qr_content', models.CharField(choices=[('website', 'Company website'), ('receipt_details', 'Receipt details')], default='website', max_length=32)),
                ('receipt_qr_website', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pos_settings', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Shop POS settings',
                'verbose_name_plural': 'Shop POS settings',
            },
        ),
    ]
