# Generated by Django 5.0.14 on 2026-09-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0054_shoppossettings_pos_override_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypossettings',
            name='enable_receipt_payment_methods',
            field=models.BooleanField(default=True, help_text='Show how the customer paid and M-Pesa collection details on receipts.'),
        ),
        migrations.AddField(
            model_name='shoppossettings',
            name='enable_receipt_payment_methods',
            field=models.BooleanField(default=True, help_text='Show how the customer paid and M-Pesa collection details on receipts.'),
        ),
    ]
