# Generated by Django 5.0.14 on 2026-09-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0055_enable_receipt_payment_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypossettings',
            name='mpesa_phone_number',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='shoppossettings',
            name='mpesa_phone_number',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='companypossettings',
            name='mpesa_collection_type',
            field=models.CharField(blank=True, choices=[('paybill', 'Paybill'), ('buy_goods', 'Buy Goods'), ('send_money', 'Send Money'), ('pochi', 'Pochi la Biashara')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='shoppossettings',
            name='mpesa_collection_type',
            field=models.CharField(blank=True, choices=[('paybill', 'Paybill'), ('buy_goods', 'Buy Goods'), ('send_money', 'Send Money'), ('pochi', 'Pochi la Biashara')], default='', max_length=16),
        ),
    ]
