# Generated by Django 5.0.14 on 2026-09-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0058_shopreceipt_confirmed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypossettings',
            name='enable_trade_out',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companypossettings',
            name='receipt_format_trade_out',
            field=models.CharField(default='T', max_length=8),
        ),
        migrations.AddField(
            model_name='shoppossettings',
            name='enable_trade_out',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shoppossettings',
            name='receipt_format_trade_out',
            field=models.CharField(default='T', max_length=8),
        ),
        migrations.AddField(
            model_name='shopreceipt',
            name='settled_from_trade',
            field=models.BooleanField(db_index=True, default=False, help_text='True when this sale was converted from a cleared trade-out receipt.'),
        ),
        migrations.AddField(
            model_name='shopreceipt',
            name='trade_exchange_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cumulative buying value of items stocked in to clear a trade-out.', max_digits=12),
        ),
        migrations.AddField(
            model_name='shopreceipt',
            name='trade_settlements',
            field=models.JSONField(blank=True, default=list, help_text='Trade-out settlement events: [{type, amount|value, method?, item_id?, item_name?, qty?, buying_price?, stock_movement_id?, at, by_id}, ...].'),
        ),
        migrations.AlterField(
            model_name='shopreceipt',
            name='kind',
            field=models.CharField(choices=[('sale', 'Sale'), ('credit', 'Credit'), ('quotation', 'Quotation'), ('trade_out', 'Trade out')], db_index=True, default='sale', max_length=16),
        ),
    ]
