# Generated by Django 5.0.14 on 2026-10-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0068_expense_cash_mpesa_amounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopreceiptline',
            name='return_batches',
            field=models.JSONField(blank=True, default=list, help_text='Per-return events: [{qty, at, by_id, serials, reason}, ...]. Used so stock reports attribute returns to the day they happened.'),
        ),
    ]
