# Common dial codes with ISO country codes for flagcdn.com
COUNTRY_DIAL_CODES = [
    {"iso": "KE", "name": "Kenya", "dial": "+254", "flag": "🇰🇪"},
    {"iso": "UG", "name": "Uganda", "dial": "+256", "flag": "🇺🇬"},
    {"iso": "TZ", "name": "Tanzania", "dial": "+255", "flag": "🇹🇿"},
    {"iso": "RW", "name": "Rwanda", "dial": "+250", "flag": "🇷🇼"},
    {"iso": "ET", "name": "Ethiopia", "dial": "+251", "flag": "🇪🇹"},
    {"iso": "SS", "name": "South Sudan", "dial": "+211", "flag": "🇸🇸"},
    {"iso": "SO", "name": "Somalia", "dial": "+252", "flag": "🇸🇴"},
    {"iso": "DJ", "name": "Djibouti", "dial": "+253", "flag": "🇩🇯"},
    {"iso": "ER", "name": "Eritrea", "dial": "+291", "flag": "🇪🇷"},
    {"iso": "ZA", "name": "South Africa", "dial": "+27", "flag": "🇿🇦"},
    {"iso": "NG", "name": "Nigeria", "dial": "+234", "flag": "🇳🇬"},
    {"iso": "GH", "name": "Ghana", "dial": "+233", "flag": "🇬🇭"},
    {"iso": "EG", "name": "Egypt", "dial": "+20", "flag": "🇪🇬"},
    {"iso": "MA", "name": "Morocco", "dial": "+212", "flag": "🇲🇦"},
    {"iso": "AE", "name": "United Arab Emirates", "dial": "+971", "flag": "🇦🇪"},
    {"iso": "SA", "name": "Saudi Arabia", "dial": "+966", "flag": "🇸🇦"},
    {"iso": "IN", "name": "India", "dial": "+91", "flag": "🇮🇳"},
    {"iso": "CN", "name": "China", "dial": "+86", "flag": "🇨🇳"},
    {"iso": "GB", "name": "United Kingdom", "dial": "+44", "flag": "🇬🇧"},
    {"iso": "US", "name": "United States", "dial": "+1", "flag": "🇺🇸"},
    {"iso": "CA", "name": "Canada", "dial": "+1", "flag": "🇨🇦"},
    {"iso": "AU", "name": "Australia", "dial": "+61", "flag": "🇦🇺"},
    {"iso": "DE", "name": "Germany", "dial": "+49", "flag": "🇩🇪"},
    {"iso": "FR", "name": "France", "dial": "+33", "flag": "🇫🇷"},
    {"iso": "IT", "name": "Italy", "dial": "+39", "flag": "🇮🇹"},
    {"iso": "ES", "name": "Spain", "dial": "+34", "flag": "🇪🇸"},
    {"iso": "NL", "name": "Netherlands", "dial": "+31", "flag": "🇳🇱"},
    {"iso": "BE", "name": "Belgium", "dial": "+32", "flag": "🇧🇪"},
    {"iso": "CH", "name": "Switzerland", "dial": "+41", "flag": "🇨🇭"},
    {"iso": "SE", "name": "Sweden", "dial": "+46", "flag": "🇸🇪"},
    {"iso": "NO", "name": "Norway", "dial": "+47", "flag": "🇳🇴"},
    {"iso": "DK", "name": "Denmark", "dial": "+45", "flag": "🇩🇰"},
    {"iso": "FI", "name": "Finland", "dial": "+358", "flag": "🇫🇮"},
    {"iso": "IE", "name": "Ireland", "dial": "+353", "flag": "🇮🇪"},
    {"iso": "PT", "name": "Portugal", "dial": "+351", "flag": "🇵🇹"},
    {"iso": "PL", "name": "Poland", "dial": "+48", "flag": "🇵🇱"},
    {"iso": "TR", "name": "Turkey", "dial": "+90", "flag": "🇹🇷"},
    {"iso": "BR", "name": "Brazil", "dial": "+55", "flag": "🇧🇷"},
    {"iso": "MX", "name": "Mexico", "dial": "+52", "flag": "🇲🇽"},
    {"iso": "JP", "name": "Japan", "dial": "+81", "flag": "🇯🇵"},
    {"iso": "KR", "name": "South Korea", "dial": "+82", "flag": "🇰🇷"},
    {"iso": "SG", "name": "Singapore", "dial": "+65", "flag": "🇸🇬"},
    {"iso": "MY", "name": "Malaysia", "dial": "+60", "flag": "🇲🇾"},
    {"iso": "PH", "name": "Philippines", "dial": "+63", "flag": "🇵🇭"},
    {"iso": "ID", "name": "Indonesia", "dial": "+62", "flag": "🇮🇩"},
    {"iso": "PK", "name": "Pakistan", "dial": "+92", "flag": "🇵🇰"},
    {"iso": "BD", "name": "Bangladesh", "dial": "+880", "flag": "🇧🇩"},
    {"iso": "NZ", "name": "New Zealand", "dial": "+64", "flag": "🇳🇿"},
    {"iso": "IL", "name": "Israel", "dial": "+972", "flag": "🇮🇱"},
    {"iso": "QA", "name": "Qatar", "dial": "+974", "flag": "🇶🇦"},
]
