from django.urls import path

from shops import views as shop_views

from . import analytics_views, converters, hr_views, views  # noqa: F401 — registers role_segment converter
from communications import views as communications_views

urlpatterns = [
    path("my-shop/", shop_views.my_shop_entry, name="my_shop"),
    path("my-shop/select/", shop_views.my_shop_select, name="my_shop_select"),
    path("my-shop/leave/", shop_views.my_shop_leave, name="my_shop_leave"),
    path("shops/login/", shop_views.shop_portal_login, name="shop_login"),
    path("shops/logout/", shop_views.shop_portal_logout, name="shop_logout"),
    path(
        "shop/<int:shop_id>/",
        shop_views.shop_website,
        name="shop_website",
    ),
    path(
        "shop/<int:shop_id>/items/<int:item_id>/suggestions/",
        shop_views.shop_website_suggestions,
        name="shop_website_suggestions",
    ),
    path(
        "my-shop/<int:shop_id>/",
        shop_views.my_shop_workspace,
        name="my_shop_workspace",
    ),
    path(
        "my-shop/<int:shop_id>/catalog/",
        shop_views.my_shop_catalog,
        name="my_shop_catalog",
    ),
    path(
        "my-shop/<int:shop_id>/buy-stock/",
        shop_views.my_shop_buy_stock,
        name="my_shop_buy_stock",
    ),
    path(
        "my-shop/<int:shop_id>/buy-stock/catalog/",
        shop_views.my_shop_buy_stock_catalog,
        name="my_shop_buy_stock_catalog",
    ),
    path(
        "my-shop/<int:shop_id>/buy-stock/suppliers/",
        shop_views.my_shop_supplier_search,
        name="my_shop_supplier_search",
    ),
    path(
        "my-shop/<int:shop_id>/stock-requests/",
        shop_views.my_shop_stock_requests,
        name="my_shop_stock_requests",
    ),
    path(
        "my-shop/<int:shop_id>/stock-requests/create/",
        shop_views.my_shop_stock_request_create,
        name="my_shop_stock_request_create",
    ),
    path(
        "my-shop/<int:shop_id>/stock-requests/from-stock/",
        shop_views.my_shop_stock_request_from_stock,
        name="my_shop_stock_request_from_stock",
    ),
    path(
        "my-shop/<int:shop_id>/stock-requests/status/",
        shop_views.my_shop_stock_request_status,
        name="my_shop_stock_request_status",
    ),
    path(
        "my-shop/<int:shop_id>/stock-requests/supplier-ack/",
        shop_views.my_shop_stock_request_supplier_ack,
        name="my_shop_stock_request_supplier_ack",
    ),
    path(
        "my-shop/<int:shop_id>/register-expense/",
        shop_views.my_shop_register_expense,
        name="my_shop_register_expense",
    ),
    path(
        "my-shop/<int:shop_id>/receipts/",
        shop_views.my_shop_receipts,
        name="my_shop_receipts",
    ),
    path(
        "my-shop/<int:shop_id>/receipts/list/",
        shop_views.my_shop_receipts_list,
        name="my_shop_receipts_list",
    ),
    path(
        "my-shop/<int:shop_id>/receipts/<int:receipt_id>/",
        shop_views.my_shop_receipt_detail,
        name="my_shop_receipt_detail",
    ),
    path(
        "my-shop/<int:shop_id>/receipts/<int:receipt_id>/return/",
        shop_views.my_shop_receipt_return,
        name="my_shop_receipt_return",
    ),
    path(
        "my-shop/<int:shop_id>/reprint/",
        shop_views.my_shop_reprint,
        name="my_shop_reprint",
    ),
    path(
        "my-shop/<int:shop_id>/day/",
        shop_views.my_shop_day_toggle,
        name="my_shop_day_toggle",
    ),
    path(
        "my-shop/<int:shop_id>/verify-login-code/",
        shop_views.my_shop_verify_login_code,
        name="my_shop_verify_login_code",
    ),
    path(
        "my-shop/<int:shop_id>/checkout/",
        shop_views.my_shop_checkout,
        name="my_shop_checkout",
    ),
    path(
        "my-shop/<int:shop_id>/mpesa/stk/",
        shop_views.my_shop_stk_initiate,
        name="my_shop_stk_initiate",
    ),
    path(
        "my-shop/<int:shop_id>/mpesa/stk/<uuid:payment_id>/",
        shop_views.my_shop_stk_status,
        name="my_shop_stk_status",
    ),
    path(
        "mpesa/daraja/callback/",
        shop_views.daraja_stk_callback,
        name="daraja_stk_callback",
    ),
    path(
        "twilio/status/",
        communications_views.twilio_status_callback,
        name="twilio_status",
    ),
    path(
        "my-shop/<int:shop_id>/print-relay/",
        shop_views.my_shop_print_relay,
        name="my_shop_print_relay",
    ),
    path(
        "my-shop/<int:shop_id>/wifi-printers/scan/",
        shop_views.my_shop_wifi_printer_scan,
        name="my_shop_wifi_printer_scan",
    ),
    path(
        "my-shop/<int:shop_id>/clients/lookup/",
        shop_views.my_shop_client_lookup,
        name="my_shop_client_lookup",
    ),
    path(
        "my-shop/<int:shop_id>/serials/search/",
        shop_views.my_shop_serial_search,
        name="my_shop_serial_search",
    ),
    path(
        "my-shop/<int:shop_id>/stock-requests/<int:request_id>/respond/",
        shop_views.my_shop_stock_request_respond,
        name="my_shop_stock_request_respond",
    ),
    path(
        "my-shop/<int:shop_id>/stock-requests/<int:request_id>/result-ack/",
        shop_views.my_shop_stock_request_result_ack,
        name="my_shop_stock_request_result_ack",
    ),
    path(
        "my-shop/<int:shop_id>/stock-requests/results-ack-all/",
        shop_views.my_shop_stock_request_results_ack_all,
        name="my_shop_stock_request_results_ack_all",
    ),
    path("employee/", views.role_employee, name="role_employee"),
    path(
        "super-admin/employees/<str:employee_id>/access/",
        views.update_employee_access,
        name="update_employee_access",
    ),
    path(
        "super-admin/<int:page>/",
        views.role_super_admin,
        name="role_super_admin_page",
    ),
    path("super-admin/", views.role_super_admin, name="role_super_admin"),
    path(
        "company-manager/",
        views.role_company_manager,
        name="role_company_manager",
    ),
    path("shop-manager/", views.role_shop_manager, name="role_shop_manager"),
    path("shop-cashier/", views.role_shop_cashier, name="role_shop_cashier"),
    path("it-support/", views.role_it_support, name="role_it_support"),
    path("it-support/marketing/", views.marketing_links, name="marketing_links"),
    path(
        "<role_segment:role_segment>/hr-management/approvals/<int:page>/",
        hr_views.hr_employee_approvals,
        name="hr_employee_approvals_page",
    ),
    path(
        "<role_segment:role_segment>/hr-management/approvals/",
        hr_views.hr_employee_approvals,
        name="hr_employee_approvals",
    ),
    path(
        "<role_segment:role_segment>/hr-management/<int:page>/",
        hr_views.hr_management_page,
        name="hr_management_page",
    ),
    path(
        "<role_segment:role_segment>/hr-management/",
        hr_views.hr_management_page,
        name="hr_management",
    ),
    path(
        "<role_segment:role_segment>/hr-management/<slug:section>/",
        hr_views.hr_section,
        name="hr_section",
    ),
    path(
        "<role_segment:role_segment>/stock-management/catalog/",
        views.stock_management_catalog_proxy,
        name="stock_management_catalog",
    ),
    path(
        "<role_segment:role_segment>/stock-management/print/",
        views.stock_management_print_proxy,
        name="stock_management_print",
    ),
    path(
        "<role_segment:role_segment>/stock-management/serials/returns/guest/",
        views.stock_serial_return_guest_page,
        name="stock_serial_return_guest",
    ),
    path(
        "<role_segment:role_segment>/stock-management/serials/returns/<int:client_id>/",
        views.stock_serial_return_client_page,
        name="stock_serial_return_client",
    ),
    path(
        "<role_segment:role_segment>/stock-management/serials/<int:item_id>/",
        views.stock_serial_detail_page,
        name="stock_serial_detail",
    ),
    path(
        "<role_segment:role_segment>/stock-management/serials/<int:item_id>/<str:serial_number>/",
        views.stock_serial_history_page,
        name="stock_serial_history",
    ),
    path(
        "<role_segment:role_segment>/item-management/catalog/",
        views.item_management_catalog_proxy,
        name="item_management_catalog",
    ),
    path(
        "<role_segment:role_segment>/analytics/account-pay/",
        analytics_views.analytics_account_pay,
        name="analytics_account_pay",
    ),
    path(
        "<role_segment:role_segment>/analytics/account-pay/stk/",
        analytics_views.analytics_account_pay_stk,
        name="analytics_account_pay_stk",
    ),
    path(
        "<role_segment:role_segment>/analytics/account-pay/stk/<uuid:payment_id>/",
        analytics_views.analytics_account_pay_stk_status,
        name="analytics_account_pay_stk_status",
    ),
    path(
        "<role_segment:role_segment>/analytics/credit-receipt/<int:receipt_id>/due-date/",
        analytics_views.analytics_credit_receipt_update,
        name="analytics_credit_receipt_update",
    ),
    path(
        "<role_segment:role_segment>/analytics/credits/audits/",
        analytics_views.analytics_credit_audits,
        name="analytics_credit_audits",
    ),
    path(
        "<role_segment:role_segment>/analytics/suppliers/<slug:kind>/<int:supplier_id>/",
        analytics_views.analytics_supplier_account,
        name="analytics_supplier_account",
    ),
    path(
        "<role_segment:role_segment>/analytics/clients/<int:client_id>/payments/",
        analytics_views.analytics_client_credit_audit,
        name="analytics_client_credit_audit",
    ),
    path(
        "<role_segment:role_segment>/analytics/clients/<int:client_id>/",
        analytics_views.analytics_client_credit,
        name="analytics_client_account",
    ),
    path(
        "<role_segment:role_segment>/analytics/credits/clients/<int:client_id>/",
        analytics_views.analytics_client_credit,
        name="analytics_client_credit",
    ),
    path(
        "<role_segment:role_segment>/analytics/receipts/<slug:kind>/",
        analytics_views.analytics_receipts_list,
        name="analytics_receipts_list",
    ),
    path(
        "<role_segment:role_segment>/analytics/api/receipts/verify-login/",
        analytics_views.analytics_receipt_verify_login,
        name="analytics_receipt_verify_login",
    ),
    path(
        "<role_segment:role_segment>/analytics/api/receipts/<int:shop_id>/<int:receipt_id>/",
        analytics_views.analytics_receipt_detail,
        name="analytics_receipt_detail",
    ),
    path(
        "<role_segment:role_segment>/analytics/api/receipts/<int:shop_id>/<int:receipt_id>/return/",
        analytics_views.analytics_receipt_return,
        name="analytics_receipt_return",
    ),
    path(
        "<role_segment:role_segment>/analytics/<slug:section>/",
        analytics_views.analytics_section,
        name="analytics_section",
    ),
    path(
        "<role_segment:role_segment>/whatsapp/catalogue/",
        communications_views.whatsapp_catalogue,
        name="whatsapp_catalogue",
    ),
    path(
        "<role_segment:role_segment>/whatsapp/contacts/",
        communications_views.whatsapp_contacts,
        name="whatsapp_contacts",
    ),
    path(
        "<role_segment:role_segment>/marketing/activities/",
        communications_views.marketing_activities,
        name="marketing_activities",
    ),
    path(
        "<role_segment:role_segment>/whatsapp/api/status/",
        communications_views.communications_api_status,
        name="whatsapp_api_status",
    ),
    path(
        "<role_segment:role_segment>/whatsapp/api/inbox/",
        communications_views.communications_api_inbox,
        name="whatsapp_api_inbox",
    ),
    path(
        "<role_segment:role_segment>/whatsapp/api/analytics/",
        communications_views.communications_api_analytics,
        name="whatsapp_api_analytics",
    ),
    path(
        "<role_segment:role_segment>/whatsapp/api/logout/",
        communications_views.communications_api_logout,
        name="whatsapp_api_logout",
    ),
    path(
        "<role_segment:role_segment>/whatsapp/api/recipients/",
        communications_views.communications_api_recipients,
        name="whatsapp_api_recipients",
    ),
    path(
        "<role_segment:role_segment>/whatsapp/api/preview/",
        communications_views.communications_api_preview,
        name="whatsapp_api_preview",
    ),
    path(
        "<role_segment:role_segment>/whatsapp/api/send/",
        communications_views.communications_api_send,
        name="whatsapp_api_send",
    ),
    path(
        "<role_segment:role_segment>/whatsapp/api/campaigns/<int:campaign_id>/",
        communications_views.communications_api_campaign,
        name="whatsapp_api_campaign",
    ),
    # Legacy /communications/ → /whatsapp/
    path(
        "<role_segment:role_segment>/communications/api/status/",
        communications_views.communications_api_status,
        name="communications_api_status",
    ),
    path(
        "<role_segment:role_segment>/communications/api/inbox/",
        communications_views.communications_api_inbox,
        name="communications_api_inbox",
    ),
    path(
        "<role_segment:role_segment>/communications/api/analytics/",
        communications_views.communications_api_analytics,
        name="communications_api_analytics",
    ),
    path(
        "<role_segment:role_segment>/communications/api/logout/",
        communications_views.communications_api_logout,
        name="communications_api_logout",
    ),
    path(
        "<role_segment:role_segment>/communications/api/recipients/",
        communications_views.communications_api_recipients,
        name="communications_api_recipients",
    ),
    path(
        "<role_segment:role_segment>/communications/api/preview/",
        communications_views.communications_api_preview,
        name="communications_api_preview",
    ),
    path(
        "<role_segment:role_segment>/communications/api/send/",
        communications_views.communications_api_send,
        name="communications_api_send",
    ),
    path(
        "<role_segment:role_segment>/communications/api/campaigns/<int:campaign_id>/",
        communications_views.communications_api_campaign,
        name="communications_api_campaign",
    ),
    path(
        "<role_segment:role_segment>/communications/",
        views.legacy_communications_redirect,
        name="legacy_communications_module",
    ),
    path(
        "<role_segment:role_segment>/<slug:module_slug>/",
        views.workspace_module,
        name="workspace_module",
    ),
]
