"""
Sell-serial live search correction loop.

Reproduces the shop-floor bug where serials show on /stock-management/serials/<id>/
but the sell modal returns no matches because search hit employees:serial_search
(requires employee login) while the floor often runs on shop portal session.

Usage:
  python scripts/test_sell_serial_search_loop.py
  python scripts/test_sell_serial_search_loop.py --iterations 5
"""

from __future__ import annotations

import argparse
import os
import sys
import time
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "myshop.settings")


def django_ready() -> None:
    import django

    django.setup()


def _seed_serial_item():
    from decimal import Decimal

    from items.models import Item, ItemSerial, ShopStock
    from shops.models import Shop

    shop = (
        Shop.objects.filter(is_hidden=False, is_suspended=False)
        .order_by("pk")
        .first()
    )
    if shop is None:
        raise RuntimeError("No shop available for sell-serial loop.")

    suffix = uuid.uuid4().hex[:8].upper()
    item = Item.objects.create(
        category="LOOP TEST",
        name=f"SELL SERIAL LOOP {suffix}",
        description="Autogenerated sell-serial search fixture",
        minimum_selling_price=Decimal("100.00"),
        shop_price=Decimal("150.00"),
        stock=0,
        track_serial_number=True,
    )
    serials = [f"LOOP{suffix}A{i}" for i in range(1, 4)]
    ItemSerial.objects.bulk_create(
        [
            ItemSerial(
                item=item,
                shop=shop,
                serial_number=serial,
                is_available=True,
            )
            for serial in serials
        ]
    )
    ShopStock.objects.update_or_create(
        shop=shop,
        item=item,
        defaults={"quantity": len(serials)},
    )
    item.stock = len(serials)
    item.save(update_fields=["stock", "updated_at"])
    return shop, item, serials


def _cleanup(item) -> None:
    from items.models import Item, ItemSerial, ShopStock

    ItemSerial.objects.filter(item=item).delete()
    ShopStock.objects.filter(item=item).delete()
    Item.objects.filter(pk=item.pk).delete()


def check_service_search(shop, item, serials) -> list[tuple[str, bool, str]]:
    from items.services import search_available_serials

    checks = []
    full = search_available_serials(
        item_id=item.pk, shop_id=shop.pk, query="", match="contains", limit=12
    )
    checks.append(
        (
            "service:empty query lists in-stock",
            set(serials).issubset(set(full)),
            f"got {full}",
        )
    )

    target = serials[0]
    exact = search_available_serials(
        item_id=item.pk,
        shop_id=shop.pk,
        query=target,
        match="contains",
        limit=12,
    )
    checks.append(
        (
            "service:full serial contains",
            target in exact,
            f"q={target} -> {exact}",
        )
    )

    last4 = target[-4:]
    suffix = search_available_serials(
        item_id=item.pk,
        shop_id=shop.pk,
        query=last4,
        match="last4",
        limit=12,
    )
    checks.append(
        (
            "service:last4 suffix contains",
            target in suffix,
            f"q={last4} -> {suffix}",
        )
    )

    other_shop_id = shop.pk + 99999
    wrong_shop = search_available_serials(
        item_id=item.pk,
        shop_id=other_shop_id,
        query=target,
        match="contains",
        limit=12,
    )
    checks.append(
        (
            "service:wrong shop empty",
            wrong_shop == [],
            f"shop={other_shop_id} -> {wrong_shop}",
        )
    )

    excluded = search_available_serials(
        item_id=item.pk,
        shop_id=shop.pk,
        query="",
        match="contains",
        exclude=[target],
        limit=12,
    )
    checks.append(
        (
            "service:exclude already selected",
            target not in excluded and set(serials[1:]).issubset(set(excluded)),
            f"excluded {target}, got {excluded}",
        )
    )
    return checks


def check_urls() -> list[tuple[str, bool, str]]:
    from django.urls import reverse

    path = reverse("employees:my_shop_serial_search", kwargs={"shop_id": 1})
    emp = reverse("employees:serial_search")
    return [
        (
            "url:my_shop_serial_search",
            path.endswith("/my-shop/1/serials/search/"),
            path,
        ),
        (
            "url:employees serial_search still exists",
            "/api/serials/" in emp,
            emp,
        ),
    ]


def check_workspace_wires_shop_url(shop) -> list[tuple[str, bool, str]]:
    from django.urls import reverse

    expected = reverse(
        "employees:my_shop_serial_search", kwargs={"shop_id": shop.pk}
    )
    workspace = (ROOT / "templates" / "shops" / "my_shop_workspace.html").read_text(
        encoding="utf-8"
    )
    views_src = (ROOT / "shops" / "views.py").read_text(encoding="utf-8")
    ws_body = views_src.split("def my_shop_workspace", 1)[-1].split(
        "\ndef my_shop_", 1
    )[0]
    return [
        (
            "template:data-serial-search-url",
            'data-serial-search-url="{{ serial_search_url }}"' in workspace,
            "workspace exposes serial_search_url",
        ),
        (
            "views:workspace uses my_shop_serial_search",
            "my_shop_serial_search" in ws_body,
            "my_shop_workspace serial_search_url",
        ),
        (
            "views:endpoint defined",
            "def my_shop_serial_search" in views_src,
            "my_shop_serial_search present",
        ),
        (
            "expected path shape",
            f"/my-shop/{shop.pk}/serials/search/" in expected,
            expected,
        ),
    ]


def check_http_shop_floor_search(shop, item, serials) -> list[tuple[str, bool, str]]:
    """Hit the shop-floor search endpoint with a portal shop session."""
    from django.test import Client
    from django.urls import reverse

    from shops.session import SESSION_SHOP_KEY, SESSION_SHOP_PORTAL_KEY

    checks = []
    client = Client()
    session = client.session
    session[SESSION_SHOP_KEY] = str(shop.pk)
    session[SESSION_SHOP_PORTAL_KEY] = True
    session.save()

    url = reverse("employees:my_shop_serial_search", kwargs={"shop_id": shop.pk})
    response = client.get(
        url,
        {
            "item_id": item.pk,
            "q": serials[0],
            "match": "contains",
        },
    )
    payload = {}
    try:
        if response.status_code == 200:
            payload = response.json()
    except Exception as exc:  # noqa: BLE001
        checks.append(("http:json", False, str(exc)))
        return checks

    results = payload.get("results") if isinstance(payload, dict) else None
    checks.append(
        (
            "http:shop-floor search 200",
            response.status_code == 200 and payload.get("ok") is True,
            f"status={response.status_code} body={payload}",
        )
    )
    checks.append(
        (
            "http:shop-floor returns seeded serial",
            isinstance(results, list) and serials[0] in results,
            f"results={results}",
        )
    )

    emp = client.get(
        reverse("employees:serial_search"),
        {"item_id": item.pk, "shop_id": shop.pk, "q": serials[0]},
    )
    emp_ok_blocked = emp.status_code in (302, 401, 403)
    if emp.status_code == 200:
        try:
            emp_results = emp.json().get("results") or []
        except Exception:  # noqa: BLE001
            emp_results = []
        emp_ok_blocked = serials[0] not in emp_results
    checks.append(
        (
            "http:employees api blocked without employee login",
            emp_ok_blocked,
            f"status={emp.status_code}",
        )
    )
    return checks


def print_report(iteration: int, checks: list[tuple[str, bool, str]]) -> bool:
    print(f"\n=== Sell serial search loop iteration {iteration} ===")
    all_ok = True
    for name, ok, detail in checks:
        mark = "PASS" if ok else "FAIL"
        print(f"  [{mark}] {name} — {detail}")
        if not ok:
            all_ok = False
    return all_ok


def main() -> int:
    parser = argparse.ArgumentParser(description="Sell serial search improve loop")
    parser.add_argument("--iterations", type=int, default=3)
    args = parser.parse_args()

    django_ready()
    item = None
    try:
        shop, item, serials = _seed_serial_item()
        overall_ok = False
        for i in range(1, args.iterations + 1):
            checks: list[tuple[str, bool, str]] = []
            checks.extend(check_urls())
            checks.extend(check_workspace_wires_shop_url(shop))
            checks.extend(check_service_search(shop, item, serials))
            checks.extend(check_http_shop_floor_search(shop, item, serials))
            ok = print_report(i, checks)
            if ok:
                overall_ok = True
                print("\nAll sell-serial search checks passed.")
                break
            if i < args.iterations:
                print("  Re-running after short pause…")
                time.sleep(0.3)
        return 0 if overall_ok else 1
    finally:
        if item is not None:
            _cleanup(item)


if __name__ == "__main__":
    raise SystemExit(main())
